//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSAPortalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSAPortalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RSAPortalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string btnApprove {
            get {
                return ResourceManager.GetString("btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string btnDefault {
            get {
                return ResourceManager.GetString("btnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        internal static string btnDeny {
            get {
                return ResourceManager.GetString("btnDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string btnRequest {
            get {
                return ResourceManager.GetString("btnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string cvPassword {
            get {
                return ResourceManager.GetString("cvPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department :.
        /// </summary>
        internal static string lblDept {
            get {
                return ResourceManager.GetString("lblDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation :.
        /// </summary>
        internal static string lblDesig {
            get {
                return ResourceManager.GetString("lblDesig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string lblEmailId {
            get {
                return ResourceManager.GetString("lblEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Sent on your email id..
        /// </summary>
        internal static string lblMsgPasswordSent {
            get {
                return ResourceManager.GetString("lblMsgPasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string lblOldPassword {
            get {
                return ResourceManager.GetString("lblOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No. :.
        /// </summary>
        internal static string lblPhoneNo {
            get {
                return ResourceManager.GetString("lblPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Type Password.
        /// </summary>
        internal static string lblReTypePassword {
            get {
                return ResourceManager.GetString("lblReTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string lblTitleChangePassword {
            get {
                return ResourceManager.GetString("lblTitleChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Document Details.
        /// </summary>
        internal static string lblTitleDocDetails {
            get {
                return ResourceManager.GetString("lblTitleDocDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string lblTitleForgotPwd {
            get {
                return ResourceManager.GetString("lblTitleForgotPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string lblTitleLogin {
            get {
                return ResourceManager.GetString("lblTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval.
        /// </summary>
        internal static string lblTitleRequestApproval {
            get {
                return ResourceManager.GetString("lblTitleRequestApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Creation Form.
        /// </summary>
        internal static string lblTitleUserCreation {
            get {
                return ResourceManager.GetString("lblTitleUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email ID:.
        /// </summary>
        internal static string lblUserEmailId {
            get {
                return ResourceManager.GetString("lblUserEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name :.
        /// </summary>
        internal static string lblUserFirstName {
            get {
                return ResourceManager.GetString("lblUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name :.
        /// </summary>
        internal static string lblUserLastName {
            get {
                return ResourceManager.GetString("lblUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access level :.
        /// </summary>
        internal static string lblUserRoles {
            get {
                return ResourceManager.GetString("lblUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string lnkForgot {
            get {
                return ResourceManager.GetString("lnkForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple active sessions not allowed, you have been logged out from all sessions. Kindly Login again to proceed..
        /// </summary>
        internal static string M00001 {
            get {
                return ResourceManager.GetString("M00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session logout successfully..
        /// </summary>
        internal static string M00002 {
            get {
                return ResourceManager.GetString("M00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Username..
        /// </summary>
        internal static string M00003 {
            get {
                return ResourceManager.GetString("M00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new Password has been sent to your registered Email..
        /// </summary>
        internal static string M00004 {
            get {
                return ResourceManager.GetString("M00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been reset successfully and the user has been sent a temporary password..
        /// </summary>
        internal static string M00005 {
            get {
                return ResourceManager.GetString("M00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not sent as the username is not recognised..
        /// </summary>
        internal static string M00006 {
            get {
                return ResourceManager.GetString("M00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been applied successfully..
        /// </summary>
        internal static string M00007 {
            get {
                return ResourceManager.GetString("M00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create account as the user already exists..
        /// </summary>
        internal static string M00008 {
            get {
                return ResourceManager.GetString("M00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply changes as the maximum number of Client Admin users has been reached..
        /// </summary>
        internal static string M00009 {
            get {
                return ResourceManager.GetString("M00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply changes as the maximum number of users has been reached..
        /// </summary>
        internal static string M00010 {
            get {
                return ResourceManager.GetString("M00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply changes as the email address is already in use..
        /// </summary>
        internal static string M00011 {
            get {
                return ResourceManager.GetString("M00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account unlocked successfully..
        /// </summary>
        internal static string M00012 {
            get {
                return ResourceManager.GetString("M00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password you have entered is incorrect..
        /// </summary>
        internal static string M00013 {
            get {
                return ResourceManager.GetString("M00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has successfully been changed..
        /// </summary>
        internal static string M00014 {
            get {
                return ResourceManager.GetString("M00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters long..
        /// </summary>
        internal static string M00015 {
            get {
                return ResourceManager.GetString("M00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&amp;nbsp;- The password must be at least 8 characters long &lt;br/&gt;&lt;br/&gt;&amp;nbsp;&amp;nbsp;-  The password must contain at least three of the following: &lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;• Upper case character&lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;• Lower case character&lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;• Numeric character&lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string M00016 {
            get {
                return ResourceManager.GetString("M00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Username..
        /// </summary>
        internal static string M00017 {
            get {
                return ResourceManager.GetString("M00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password..
        /// </summary>
        internal static string M00018 {
            get {
                return ResourceManager.GetString("M00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully, please login again..
        /// </summary>
        internal static string M00019 {
            get {
                return ResourceManager.GetString("M00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session closed due to login from another browser/system..
        /// </summary>
        internal static string M00020 {
            get {
                return ResourceManager.GetString("M00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is invalid..
        /// </summary>
        internal static string M00021 {
            get {
                return ResourceManager.GetString("M00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has now expired, please change your password..
        /// </summary>
        internal static string M00022 {
            get {
                return ResourceManager.GetString("M00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked, please contact your administrator..
        /// </summary>
        internal static string M00023 {
            get {
                return ResourceManager.GetString("M00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been made inactive, please contact your administrator..
        /// </summary>
        internal static string M00024 {
            get {
                return ResourceManager.GetString("M00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous session closed. Please login again..
        /// </summary>
        internal static string M00025 {
            get {
                return ResourceManager.GetString("M00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username, account details not found..
        /// </summary>
        internal static string M00026 {
            get {
                return ResourceManager.GetString("M00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked, please contact your administrator..
        /// </summary>
        internal static string M00027 {
            get {
                return ResourceManager.GetString("M00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password is too similar to your existing one. Please choose a new password..
        /// </summary>
        internal static string M00028 {
            get {
                return ResourceManager.GetString("M00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A temporary password has been sent to your email address..
        /// </summary>
        internal static string M00029 {
            get {
                return ResourceManager.GetString("M00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reset password..
        /// </summary>
        internal static string M00030 {
            get {
                return ResourceManager.GetString("M00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change your password..
        /// </summary>
        internal static string M00031 {
            get {
                return ResourceManager.GetString("M00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password..
        /// </summary>
        internal static string M00032 {
            get {
                return ResourceManager.GetString("M00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password..
        /// </summary>
        internal static string M00033 {
            get {
                return ResourceManager.GetString("M00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters are not allowed..
        /// </summary>
        internal static string M00034 {
            get {
                return ResourceManager.GetString("M00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string M00035 {
            get {
                return ResourceManager.GetString("M00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Product..
        /// </summary>
        internal static string M00036 {
            get {
                return ResourceManager.GetString("M00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a condition for the date you have entered..
        /// </summary>
        internal static string M00037 {
            get {
                return ResourceManager.GetString("M00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid From date. It should be less than or equal to todays date..
        /// </summary>
        internal static string M00038 {
            get {
                return ResourceManager.GetString("M00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid To date. It should be less than or equal to todays date..
        /// </summary>
        internal static string M00039 {
            get {
                return ResourceManager.GetString("M00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both  From and To dates..
        /// </summary>
        internal static string M00040 {
            get {
                return ResourceManager.GetString("M00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date must be greater than the From date..
        /// </summary>
        internal static string M00041 {
            get {
                return ResourceManager.GetString("M00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one date should be entered..
        /// </summary>
        internal static string M00042 {
            get {
                return ResourceManager.GetString("M00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a condition for the page count you have entered..
        /// </summary>
        internal static string M00043 {
            get {
                return ResourceManager.GetString("M00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both From and To page count..
        /// </summary>
        internal static string M00044 {
            get {
                return ResourceManager.GetString("M00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To page count must be greater than From page count..
        /// </summary>
        internal static string M00045 {
            get {
                return ResourceManager.GetString("M00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one page count should be entered..
        /// </summary>
        internal static string M00046 {
            get {
                return ResourceManager.GetString("M00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wildcard symbol cannot be the first character of the field..
        /// </summary>
        internal static string M00047 {
            get {
                return ResourceManager.GetString("M00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sort field can only be selected once..
        /// </summary>
        internal static string M00048 {
            get {
                return ResourceManager.GetString("M00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct date..
        /// </summary>
        internal static string M00049 {
            get {
                return ResourceManager.GetString("M00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a numeric value in the field \&apos;{0}\&apos;..
        /// </summary>
        internal static string M00050 {
            get {
                return ResourceManager.GetString("M00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one column to display Search List..
        /// </summary>
        internal static string M00051 {
            get {
                return ResourceManager.GetString("M00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the position order..
        /// </summary>
        internal static string M00052 {
            get {
                return ResourceManager.GetString("M00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A position order can only be selected once..
        /// </summary>
        internal static string M00053 {
            get {
                return ResourceManager.GetString("M00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an access level for the user..
        /// </summary>
        internal static string M00054 {
            get {
                return ResourceManager.GetString("M00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Username..
        /// </summary>
        internal static string M00055 {
            get {
                return ResourceManager.GetString("M00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user&apos;s first name..
        /// </summary>
        internal static string M00056 {
            get {
                return ResourceManager.GetString("M00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user&apos;s last name..
        /// </summary>
        internal static string M00057 {
            get {
                return ResourceManager.GetString("M00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field contains invalid characters..
        /// </summary>
        internal static string M00058 {
            get {
                return ResourceManager.GetString("M00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field contains invalid characters..
        /// </summary>
        internal static string M00059 {
            get {
                return ResourceManager.GetString("M00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A temporary password has been sent to the user..
        /// </summary>
        internal static string M00060 {
            get {
                return ResourceManager.GetString("M00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session logout successfully..
        /// </summary>
        internal static string M00061 {
            get {
                return ResourceManager.GetString("M00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Date..
        /// </summary>
        internal static string M00062 {
            get {
                return ResourceManager.GetString("M00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter To Date..
        /// </summary>
        internal static string M00063 {
            get {
                return ResourceManager.GetString("M00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date must be greater than the From date..
        /// </summary>
        internal static string M00064 {
            get {
                return ResourceManager.GetString("M00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a page count..
        /// </summary>
        internal static string M00065 {
            get {
                return ResourceManager.GetString("M00065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a To page count..
        /// </summary>
        internal static string M00066 {
            get {
                return ResourceManager.GetString("M00066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid To date..
        /// </summary>
        internal static string M00067 {
            get {
                return ResourceManager.GetString("M00067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents match your search criteria..
        /// </summary>
        internal static string M00068 {
            get {
                return ResourceManager.GetString("M00068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results displayed have been limited as the returned list was too large. Please refine your search criteria..
        /// </summary>
        internal static string M00069 {
            get {
                return ResourceManager.GetString("M00069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authenticated successfully..
        /// </summary>
        internal static string M00070 {
            get {
                return ResourceManager.GetString("M00070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in User cannot change its own status..
        /// </summary>
        internal static string M00071 {
            get {
                return ResourceManager.GetString("M00071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged out, cannot proceed..
        /// </summary>
        internal static string M00072 {
            get {
                return ResourceManager.GetString("M00072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session recorded successfully..
        /// </summary>
        internal static string M00073 {
            get {
                return ResourceManager.GetString("M00073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply changes as the maximum number of users has been reached..
        /// </summary>
        internal static string M00074 {
            get {
                return ResourceManager.GetString("M00074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been expired. Please login again..
        /// </summary>
        internal static string M00075 {
            get {
                return ResourceManager.GetString("M00075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string M00076 {
            get {
                return ResourceManager.GetString("M00076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-type your password..
        /// </summary>
        internal static string M00077 {
            get {
                return ResourceManager.GetString("M00077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Alphanumeric characters without space in the Field \&apos;{0}\&apos;..
        /// </summary>
        internal static string M00078 {
            get {
                return ResourceManager.GetString("M00078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Alphanumeric characters  in the Field  \&apos;{0}\&apos;..
        /// </summary>
        internal static string M00079 {
            get {
                return ResourceManager.GetString("M00079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please contact your administrator..
        /// </summary>
        internal static string M00080 {
            get {
                return ResourceManager.GetString("M00080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during retrieval of the document: Kindly contact your Administrator..
        /// </summary>
        internal static string M00081 {
            get {
                return ResourceManager.GetString("M00081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh only works once a search has been performed..
        /// </summary>
        internal static string M00082 {
            get {
                return ResourceManager.GetString("M00082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a wildcard as part of the search it must be the last character of the search data..
        /// </summary>
        internal static string M00083 {
            get {
                return ResourceManager.GetString("M00083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to incorrect login attempts by another user, this account has been locked and this session closed..
        /// </summary>
        internal static string M00084 {
            get {
                return ResourceManager.GetString("M00084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Active Super User : 0.
        /// </summary>
        internal static string MessageForActiveSuperUser {
            get {
                return ResourceManager.GetString("MessageForActiveSuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Active User : 0.
        /// </summary>
        internal static string MessageForActiveUser {
            get {
                return ResourceManager.GetString("MessageForActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Active {0} : {1}.
        /// </summary>
        internal static string MessageForTentantUser {
            get {
                return ResourceManager.GetString("MessageForTentantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Active Client Admin : 0.
        /// </summary>
        internal static string MessageForTentantUser0 {
            get {
                return ResourceManager.GetString("MessageForTentantUser0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Username..
        /// </summary>
        internal static string revEmailId {
            get {
                return ResourceManager.GetString("revEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password cannot contain any of the following characters:    / \ ? [ ] | &lt; &gt; = , ? * { } . ` &quot;.
        /// </summary>
        internal static string revNewPassword {
            get {
                return ResourceManager.GetString("revNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Username..
        /// </summary>
        internal static string rfvEmailId {
            get {
                return ResourceManager.GetString("rfvEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password..
        /// </summary>
        internal static string rfvNewPassword {
            get {
                return ResourceManager.GetString("rfvNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password..
        /// </summary>
        internal static string rfvOldPassword {
            get {
                return ResourceManager.GetString("rfvOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password..
        /// </summary>
        internal static string rfvPassword {
            get {
                return ResourceManager.GetString("rfvPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user&apos;s first name..
        /// </summary>
        internal static string rfvUserFirstName {
            get {
                return ResourceManager.GetString("rfvUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user&apos;s last name..
        /// </summary>
        internal static string rfvUserLastName {
            get {
                return ResourceManager.GetString("rfvUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an access level for the user..
        /// </summary>
        internal static string rfvUserRole {
            get {
                return ResourceManager.GetString("rfvUserRole", resourceCulture);
            }
        }
    }
}
